import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

// Load Montserrat
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800","900"],
  variable: '--font-montserrat', 
})

export const metadata: Metadata = {
  title: "Co-connect",
  description: "Generated by co-connect",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en" className={montserrat.variable}>
    <body className="antialiased">
      {children}
    </body>
  </html>
  );
}
